<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Ejercicio 4</title>
</head>
<body>
  <h3>Unir nombre y apellido</h3>

  Nombre: 
  <input type="text" id="nombre">
  <br><br>

  Apellido: 
  <input type="text" id="apellido">
  <br><br>

  <button onclick="unirNombreApellido()">Unir</button>
  <br><br>

  Nombre completo: 
  <input type="text" id="resultado" readonly>

  <script>
    function unirNombreApellido() {
      let nom = document.getElementById("nombre").value;
      let ape = document.getElementById("apellido").value;

      let completo = nom + " " + ape;

      document.getElementById("resultado").value = completo;
    }
  </script>
</body>
</html>
