<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pizzas</title>
</head>
<body>
  <h2>Seleccionar pizza</h2>

  <label for="pizza">Tipo de pizza:</label>
  <select id="pizza" onchange="mostrarPrecio()">
    <option value="">Selecciona una opción</option>
    <option value="jamon">Jamón y Queso</option>
    <option value="muzzarella">Muzzarella</option>
    <option value="morrones">Morrones</option>
  </select>

  <br>
  <br>

  <label for="precio">Precio $:</label>
  <input type="text" id="precio" readonly>

  <script>
    function mostrarPrecio() {
      const pizza = document.getElementById("pizza").value;
      const campoPrecio = document.getElementById("precio");
      let precio = "";

      if (pizza === "jamon") {
        precio = "4500";
      } else if (pizza === "muzzarella") {
        precio = "4000";
      } else if (pizza === "morrones") {
        precio = "4800";
      } else {
        precio = "";
      }

      campoPrecio.value = precio;
    }
  </script>
</body>
</html>
